AllCops:
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'bin/*'
    - 'script/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/AbcSize:
  Max: 25